version: "3"

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    volumes:
      - '/home/.local/docker/vaultwarden/:/data/'
    restart: unless-stopped
    ports:
      - '80:80'
